version: '3.7'

services:
  gatewayserver:
    image: ostock/gatewayserver:0.0.1-SNAPSHOT
    ports:
      - "8072:8072"

    environment:


    networks:
      backend:
        aliases:
          - "gateway"
networks:
  backend:
    driver: bridge